# Generated by Django 4.2 on 2026-03-24 19:38

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('rastreamento', 'Rastreamento'), ('algar', 'Algar')], max_length=20, verbose_name='Página')),
                ('app_name', models.CharField(default='MegalinkApp', max_length=100, verbose_name='Nome do app')),
                ('card_title', models.CharField(default='Megacliente', max_length=100, verbose_name='Título do card')),
                ('card_description', models.TextField(default='O aplicativo oficial da MegaLink para autoatendimento.', verbose_name='Descrição do card')),
                ('heading', models.CharField(default='MegalinkApp', max_length=200, verbose_name='Título principal')),
                ('heading_subtitle', models.CharField(default='Completo. Simples.', max_length=200, verbose_name='Subtítulo')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(blank=True, upload_to='app/', verbose_name='Imagem')),
                ('google_play_url', models.URLField(blank=True, verbose_name='Google Play URL')),
                ('app_store_url', models.URLField(blank=True, verbose_name='App Store URL')),
            ],
            options={
                'verbose_name': 'Promoção do App',
                'verbose_name_plural': 'Promoções do App',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Imagem')),
                ('link', models.CharField(default='#', max_length=300, verbose_name='Link')),
                ('page', models.CharField(choices=[('home', 'Home'), ('algar', 'Algar')], default='home', max_length=20, verbose_name='Página')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('excerpt', models.TextField(verbose_name='Resumo')),
                ('category_tag', models.CharField(max_length=50, verbose_name='Categoria')),
                ('tag_bg_color', colorfield.fields.ColorField(default='#FFD100', image_field=None, max_length=25, samples=None, verbose_name='Cor do tag')),
                ('cover_bg_color', colorfield.fields.ColorField(default='#2323FA', image_field=None, max_length=25, samples=None, verbose_name='Cor de fundo da capa')),
                ('cover_icon_class', models.CharField(blank=True, max_length=100, verbose_name='Ícone da capa')),
                ('image', models.ImageField(blank=True, upload_to='blog/', verbose_name='Imagem')),
                ('link', models.CharField(default='#', max_length=300, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon_class', models.CharField(help_text='Ex: fa-wifi, fa-bolt', max_length=100, verbose_name='Classe do ícone')),
                ('color_class', models.CharField(help_text='Ex: bg-[#FF6905]', max_length=100, verbose_name='Classe de cor')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnergyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Classe do ícone')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Energia - Vantagem',
                'verbose_name_plural': 'Energia - Vantagens',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnergyHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(default='Economize até 20% na sua conta de energia', verbose_name='Título')),
                ('highlight_text', models.CharField(default='20%', max_length=100, verbose_name='Texto destacado')),
                ('subheading', models.TextField(default='Sem taxas, sem custo de adesão e sem instalação de placas solares.', verbose_name='Subtítulo')),
                ('badge_1', models.CharField(blank=True, default='Sem fidelidade', max_length=100, verbose_name='Badge 1')),
                ('badge_2', models.CharField(blank=True, default='100% Digital', max_length=100, verbose_name='Badge 2')),
                ('form_title', models.CharField(default='Informe seus dados para contato', max_length=200, verbose_name='Título do formulário')),
                ('form_subtitle', models.CharField(blank=True, default='Fale com um de nossos especialistas.', max_length=200, verbose_name='Subtítulo do formulário')),
                ('background_image', models.ImageField(blank=True, upload_to='energy/', verbose_name='Imagem de fundo')),
            ],
            options={
                'verbose_name': 'Energia - Hero',
                'verbose_name_plural': 'Energia - Hero',
            },
        ),
        migrations.CreateModel(
            name='EnergySavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_tag', models.CharField(default='Inovação Solar', max_length=100, verbose_name='Tag da seção')),
                ('heading', models.CharField(default='Mais economia para você', max_length=200, verbose_name='Título')),
                ('content_title', models.CharField(default='Energia por Assinatura', max_length=200, verbose_name='Título do conteúdo')),
                ('content_body', models.TextField(verbose_name='Corpo do conteúdo')),
                ('savings_percentage', models.IntegerField(default=20, verbose_name='Percentual de economia')),
                ('checkmarks', models.JSONField(default=list, help_text='Lista: ["Sem taxa de adesão", ...]', verbose_name='Checkmarks')),
                ('cta_text', models.CharField(default='Garantir meu desconto', max_length=100, verbose_name='Texto do botão')),
                ('cta_link', models.CharField(default='#', max_length=200, verbose_name='Link do botão')),
            ],
            options={
                'verbose_name': 'Energia - Economia',
                'verbose_name_plural': 'Energia - Economia',
            },
        ),
        migrations.CreateModel(
            name='EnergyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Energia - Passo',
                'verbose_name_plural': 'Energia - Passos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='InternetPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Home'), ('algar', 'Algar')], default='home', max_length=20, verbose_name='Página')),
                ('category_label', models.CharField(default='INTERNET', max_length=50, verbose_name='Categoria')),
                ('speed_value', models.CharField(max_length=10, verbose_name='Velocidade')),
                ('speed_unit', models.CharField(choices=[('MEGA', 'MEGA'), ('GIGA', 'GIGA')], default='MEGA', max_length=10, verbose_name='Unidade')),
                ('current_price', models.CharField(help_text='Ex: 89,90', max_length=20, verbose_name='Preço atual')),
                ('old_price', models.CharField(blank=True, help_text='Ex: 117,90', max_length=20, verbose_name='Preço antigo')),
                ('period', models.CharField(default='/mês', max_length=10, verbose_name='Período')),
                ('button_text', models.CharField(default='Aproveitar Oferta', max_length=50, verbose_name='Texto do botão')),
                ('button_link', models.URLField(max_length=500, verbose_name='Link do botão')),
                ('show_badge', models.BooleanField(default=False, verbose_name='Mostrar badge')),
                ('badge_text', models.CharField(blank=True, max_length=50, verbose_name='Texto do badge')),
                ('badge_bg_color', colorfield.fields.ColorField(blank=True, default='#2323FA', image_field=None, max_length=25, samples=None, verbose_name='Cor de fundo do badge')),
                ('badge_text_color', colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor do texto do badge')),
                ('title_color', colorfield.fields.ColorField(default='#2323FA', image_field=None, max_length=25, samples=None, verbose_name='Cor do título')),
                ('speed_color', colorfield.fields.ColorField(default='#2323FA', image_field=None, max_length=25, samples=None, verbose_name='Cor da velocidade')),
                ('underline_color', colorfield.fields.ColorField(default='#FF6905', image_field=None, max_length=25, samples=None, verbose_name='Cor do sublinhado')),
                ('button_bg_color', colorfield.fields.ColorField(default='#FF6905', image_field=None, max_length=25, samples=None, verbose_name='Cor do botão')),
                ('button_text_color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Cor do texto do botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Plano de Internet',
                'verbose_name_plural': 'Planos de Internet',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MegaEnergiaHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(default='Mega Energia sua conta com até', verbose_name='Título')),
                ('heading_highlight', models.CharField(default='20% de desconto', max_length=200, verbose_name='Texto destacado')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('cta_text', models.CharField(default='Quero economizar', max_length=100, verbose_name='Texto do botão')),
                ('cta_link', models.CharField(default='energia', max_length=200, verbose_name='Link do botão')),
                ('card_title', models.CharField(default='Simples e Digital', max_length=200, verbose_name='Título do card')),
                ('card_features', models.JSONField(default=list, help_text='Lista: ["Sem fidelidade", "Sem obras", ...]', verbose_name='Itens do card')),
            ],
            options={
                'verbose_name': 'Mega Energia (Home)',
                'verbose_name_plural': 'Mega Energia (Home)',
            },
        ),
        migrations.CreateModel(
            name='SelfServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon_class', models.CharField(help_text='Ex: fa-solid fa-file-invoice', max_length=100, verbose_name='Classe do ícone')),
                ('link', models.CharField(default='#', max_length=300, verbose_name='Link')),
                ('highlight', models.BooleanField(default=False, verbose_name='Destacar (azul)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Item de Autoatendimento',
                'verbose_name_plural': 'Itens de Autoatendimento',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('icon_class', models.CharField(blank=True, help_text='FontAwesome class (opcional, usa SVG por padrão)', max_length=100, verbose_name='Classe do ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrackingBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Classe do ícone')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Rastreamento - Benefício',
                'verbose_name_plural': 'Rastreamento - Benefícios',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrackingCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(verbose_name='Título')),
                ('subheading', models.TextField(verbose_name='Subtítulo')),
                ('primary_button_text', models.CharField(max_length=200, verbose_name='Botão primário')),
                ('primary_button_link', models.URLField(verbose_name='Link botão primário')),
                ('secondary_button_text', models.CharField(blank=True, max_length=200, verbose_name='Botão secundário')),
                ('secondary_button_link', models.CharField(blank=True, max_length=200, verbose_name='Link botão secundário')),
                ('footnote', models.CharField(blank=True, max_length=300, verbose_name='Rodapé')),
            ],
            options={
                'verbose_name': 'Rastreamento - CTA',
                'verbose_name_plural': 'Rastreamento - CTA',
            },
        ),
        migrations.CreateModel(
            name='TrackingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100, verbose_name='Classe do ícone')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Rastreamento - Funcionalidade',
                'verbose_name_plural': 'Rastreamento - Funcionalidades',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(default='Monitoramento 24h', max_length=100, verbose_name='Tag')),
                ('heading', models.TextField(verbose_name='Título')),
                ('subheading', models.TextField(verbose_name='Subtítulo')),
                ('cta_text', models.CharField(blank=True, max_length=200, verbose_name='Texto do botão')),
                ('cta_link', models.CharField(default='#contratar', max_length=200, verbose_name='Link do botão')),
                ('form_title', models.CharField(blank=True, max_length=200, verbose_name='Título do formulário')),
                ('form_subtitle', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo do formulário')),
                ('background_image', models.ImageField(blank=True, upload_to='tracking/', verbose_name='Imagem de fundo')),
            ],
            options={
                'verbose_name': 'Rastreamento - Hero',
                'verbose_name_plural': 'Rastreamento - Hero',
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Texto')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.internetplan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Feature do Plano',
                'verbose_name_plural': 'Features do Plano',
                'ordering': ['order'],
            },
        ),
    ]
