# Generated by Django 4.2 on 2026-03-24 19:38

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Coluna do Rodapé',
                'verbose_name_plural': 'Colunas do Rodapé',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Coluna do Mega Menu',
                'verbose_name_plural': 'Colunas do Mega Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MegaLink', max_length=100, verbose_name='Nome da empresa')),
                ('logo', models.ImageField(blank=True, upload_to='config/', verbose_name='Logo')),
                ('logo_alt_text', models.CharField(default='MegaLink Provedor', max_length=100, verbose_name='Alt do logo')),
                ('favicon', models.ImageField(blank=True, upload_to='config/', verbose_name='Favicon')),
                ('primary_color', colorfield.fields.ColorField(default='#2323FA', image_field=None, max_length=25, samples=None, verbose_name='Cor primária')),
                ('primary_dark_color', colorfield.fields.ColorField(default='#040470', image_field=None, max_length=25, samples=None, verbose_name='Cor primária escura')),
                ('secondary_color', colorfield.fields.ColorField(default='#FF6905', image_field=None, max_length=25, samples=None, verbose_name='Cor secundária')),
                ('accent_color', colorfield.fields.ColorField(default='#10B981', image_field=None, max_length=25, samples=None, verbose_name='Cor de destaque')),
                ('whatsapp_number', models.CharField(default='558922210068', max_length=20, verbose_name='WhatsApp')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('assine_ja_enabled', models.BooleanField(default=True, verbose_name='Botão "Assine já" ativo')),
                ('assine_ja_link', models.CharField(default='#assine', max_length=200, verbose_name='Link "Assine já"')),
                ('area_cliente_enabled', models.BooleanField(default=True, verbose_name='Botão "Área do Cliente" ativo')),
                ('area_cliente_link', models.CharField(default='#area-cliente', max_length=200, verbose_name='Link "Área do Cliente"')),
                ('footer_text', models.CharField(blank=True, default='A melhor conexão para você e sua empresa.', max_length=300, verbose_name='Texto do rodapé')),
                ('company_address', models.CharField(blank=True, max_length=300, verbose_name='Endereço empresa')),
                ('company_phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone empresa')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail empresa')),
                ('footer_copyright', models.CharField(blank=True, default='Copyright 2025 © - MegaLink - Todos os direitos reservados', max_length=300, verbose_name='Copyright')),
                ('footer_terms_url', models.CharField(blank=True, default='#termos', max_length=200, verbose_name='URL Termos')),
                ('footer_privacy_url', models.CharField(blank=True, default='#privacidade', max_length=200, verbose_name='URL Privacidade')),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
                ('menu_location', models.CharField(choices=[('main', 'Menu Principal'), ('algar', 'Menu Algar')], default='main', max_length=20, verbose_name='Localização')),
                ('is_mega_menu', models.BooleanField(default=False, verbose_name='Mega menu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Item pai')),
            ],
            options={
                'verbose_name': 'Item do Menu',
                'verbose_name_plural': 'Itens do Menu',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('link', models.CharField(default='#', max_length=200, verbose_name='Link')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.megamenucolumn', verbose_name='Coluna')),
            ],
            options={
                'verbose_name': 'Link do Mega Menu',
                'verbose_name_plural': 'Links do Mega Menu',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='megamenucolumn',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='core.menuitem', verbose_name='Item do menu'),
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('open_new_tab', models.BooleanField(default=False, verbose_name='Abrir em nova aba')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footercolumn', verbose_name='Coluna')),
            ],
            options={
                'verbose_name': 'Link do Rodapé',
                'verbose_name_plural': 'Links do Rodapé',
                'ordering': ['order'],
            },
        ),
    ]
