# Generated by Django 5.2.4 on 2026-03-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_body_scripts',
            field=models.TextField(blank=True, help_text='Scripts adicionais antes do </body>', verbose_name='Scripts no <body>'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_head_scripts',
            field=models.TextField(blank=True, help_text='Scripts adicionais no <head> (Google Analytics, etc.)', verbose_name='Scripts no <head>'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='facebook_pixel_id',
            field=models.CharField(blank=True, help_text='Ex: 1234567890123456', max_length=30, verbose_name='Facebook Pixel ID'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='gtm_id',
            field=models.CharField(blank=True, help_text='Ex: GTM-XXXXXXX', max_length=20, verbose_name='Google Tag Manager ID'),
        ),
    ]
