# Generated by Django 5.2.4 on 2026-03-25 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Código')),
                ('destination_url', models.URLField(max_length=2000, verbose_name='URL de destino')),
                ('title', models.CharField(blank=True, help_text='Nome interno para identificar o link', max_length=200, verbose_name='Título')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Link Curto',
                'verbose_name_plural': 'Links Curtos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShortLinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, verbose_name='Clicado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('referer', models.URLField(blank=True, max_length=2000, verbose_name='Referer')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='shortener.shortlink')),
            ],
            options={
                'verbose_name': 'Clique',
                'verbose_name_plural': 'Cliques',
                'ordering': ['-clicked_at'],
                'indexes': [models.Index(fields=['link', 'clicked_at'], name='shortener_s_link_id_7e1d46_idx')],
            },
        ),
    ]
