# Generated by Django 5.2.4 on 2026-03-25 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('file', models.FileField(upload_to='library/%Y/%m/', verbose_name='Arquivo')),
                ('file_type', models.CharField(choices=[('image', 'Imagem'), ('document', 'Documento'), ('video', 'Vídeo')], default='image', max_length=20, verbose_name='Tipo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='Tamanho (bytes)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Largura')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Altura')),
                ('alt_text', models.CharField(blank=True, max_length=300, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Arquivo',
                'verbose_name_plural': 'Arquivos',
                'ordering': ['-created_at'],
            },
        ),
    ]
