# Generated by Django 4.2 on 2026-03-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('energia', 'Energia'), ('rastreamento', 'Rastreamento'), ('internet', 'Internet'), ('geral', 'Geral')], default='geral', max_length=20, verbose_name='Origem')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('cep', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('media_conta', models.CharField(blank=True, max_length=100, verbose_name='Média de conta de energia')),
                ('tipo_veiculo', models.CharField(blank=True, max_length=100, verbose_name='Tipo de veículo')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('webhook_sent', models.BooleanField(default=False, verbose_name='Webhook enviado')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
