# Generated by Django 4.2 on 2026-03-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='fa-solid fa-cube', help_text='Classe FontAwesome', max_length=100, verbose_name='Ícone')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
                ('template_name', models.CharField(help_text='Ex: components/hero.html', max_length=200, verbose_name='Template')),
                ('schema', models.JSONField(default=list, help_text='Lista de campos: [{"name": "title", "type": "text", "label": "Título", "required": true}, ...]', verbose_name='Schema dos campos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tipo de Componente',
                'verbose_name_plural': 'Tipos de Componente',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(help_text='Ex: black-friday, planos-empresariais', max_length=200, unique=True, verbose_name='URL')),
                ('meta_description', models.CharField(blank=True, max_length=300, verbose_name='Meta descrição')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada')], default='draft', max_length=20, verbose_name='Status')),
                ('is_homepage', models.BooleanField(default=False, help_text='Apenas uma página pode ser a inicial', verbose_name='É a página inicial?')),
                ('show_header', models.BooleanField(default=True, verbose_name='Mostrar header')),
                ('show_footer', models.BooleanField(default=True, verbose_name='Mostrar footer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PageComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict, help_text='Dados do componente (segue o schema do tipo)', verbose_name='Conteúdo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('css_classes', models.CharField(blank=True, help_text='Tailwind classes adicionais para este bloco', max_length=500, verbose_name='Classes CSS extras')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='builder.componenttype', verbose_name='Tipo de componente')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='builder.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Componente da Página',
                'verbose_name_plural': 'Componentes da Página',
                'ordering': ['order'],
            },
        ),
    ]
