# Generated by Django 5.2.4 on 2026-03-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['slug'], name='builder_pag_slug_acabbd_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['status'], name='builder_pag_status_e76792_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_homepage', 'status'], name='builder_pag_is_home_0cfe74_idx'),
        ),
        migrations.AddIndex(
            model_name='pagecomponent',
            index=models.Index(fields=['page', 'order'], name='builder_pag_page_id_b41696_idx'),
        ),
    ]
