# Generated by Django 5.2.4 on 2026-03-25 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_page_builder_pag_slug_acabbd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='URL canônica'),
        ),
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para SEO (max 70 chars)', max_length=70, verbose_name='Meta título'),
        ),
        migrations.AddField(
            model_name='page',
            name='noindex',
            field=models.BooleanField(default=False, verbose_name='Bloquear indexação'),
        ),
        migrations.AddField(
            model_name='page',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='seo/', verbose_name='Imagem OG'),
        ),
        migrations.AddField(
            model_name='page',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Agendar publicação automática', null=True, verbose_name='Publicar em'),
        ),
        migrations.AddField(
            model_name='page',
            name='unpublish_at',
            field=models.DateTimeField(blank=True, help_text='Agendar despublicação automática', null=True, verbose_name='Despublicar em'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicada'), ('scheduled', 'Agendada')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='PageRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(verbose_name='Revisão')),
                ('data', models.JSONField(default=list, help_text='Array com dados de todos os componentes', verbose_name='Snapshot dos componentes')),
                ('page_meta', models.JSONField(default=dict, verbose_name='Metadados da página')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('comment', models.CharField(blank=True, max_length=300, verbose_name='Comentário')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='builder.page', verbose_name='Página')),
            ],
            options={
                'verbose_name': 'Revisão',
                'verbose_name_plural': 'Revisões',
                'ordering': ['-revision_number'],
                'unique_together': {('page', 'revision_number')},
            },
        ),
    ]
