# Generated by Django 5.2.4 on 2026-03-25 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_page_canonical_url_page_meta_title_page_noindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Descrição')),
                ('thumbnail', models.ImageField(blank=True, upload_to='templates/', verbose_name='Thumbnail')),
                ('components_data', models.JSONField(default=list, help_text='Snapshot dos componentes', verbose_name='Componentes')),
                ('page_defaults', models.JSONField(default=dict, help_text='show_header, show_footer, etc.', verbose_name='Config padrão')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Página',
                'verbose_name_plural': 'Templates de Página',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='builder.page')),
            ],
            options={
                'verbose_name': 'Pageview',
                'verbose_name_plural': 'Pageviews',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['page', 'date'], name='builder_pag_page_id_15a0e4_idx')],
                'unique_together': {('page', 'date')},
            },
        ),
    ]
